In [16]:
import numpy as np
import math
from random import random

In [25]:
def crossProduct(u, v):
    uXv = [
            u[1]*v[2]-u[2]*v[1], 
            u[2]*v[0]-u[0]*v[2], 
            u[0]*v[1]-u[1]*v[0]
            ]
    
    return uXv
        

In [26]:
# Construct Arrays
n = 5
u = []
v = []
for i in range(n):
    u.append([100*random(),100*random(),100*random()])
    v.append([100*random(),100*random(),100*random()])
    
uXv = []
for i in range(len(u)):
    uXv.append(crossProduct(u[i], v[i]))

print(uXv)

[[-1552.0464557921728, 2437.208672302462, 11.82674242737005], [1271.862017543072, 2176.7145572988056, -2714.247635882165], [-245.73833563272706, -2193.1650360703816, 1144.3824991002175], [4404.709365023707, -2007.7301784003967, -446.2489997547568], [-5268.497586728037, 3177.3946677089643, 4157.323477716576]]


In [27]:
# using numpy
u = np.array(u)
v = np.array(v)

uXv = np.cross(u,v)

print(uXv)

[[-1552.04645579  2437.2086723     11.82674243]
 [ 1271.86201754  2176.7145573  -2714.24763588]
 [ -245.73833563 -2193.16503607  1144.3824991 ]
 [ 4404.70936502 -2007.7301784   -446.24899975]
 [-5268.49758673  3177.39466771  4157.32347772]]
